# Generated by Django 5.1.7 on 2025-06-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_timestamps'),
        ('accounts', '0002_initial'),
    ]

    operations = [
    ]
