# ... existing code ...

urlpatterns = [
    # ... existing code ...
    path('api/transactions/', include('transactions.urls')),
    path('api/categories/', include('categories.urls')),
    # ... existing code ...
]
